### ISSUE TITLE
Example dataset has issues

### ISSUE THREAD

**Issue by noorul** [tuplejump/FiloDB#48] opened 2015-12-19 01:47 UTC
[2015-12-19 06:42:31,649] ERROR f.c.r.Scheduler [filo-cli-akka.actor.default-dispatcher-5] - Reprojection task (gdelt,0) failed
com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured columnfamily gdelt_chunkmap
        at com.datastax.driver.core.Responses$Error.asException(Responses.java:124) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:120) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:186) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at com.datastax.driver.core.RequestHandler.access$2300(RequestHandler.java:45) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:754) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:576) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:994) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:916) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) ~[filo-cli-0.1-SNAPSHOT:0.1-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_51]
[2015-12-19 06:42:32,062] ERROR com.websudos.phantom [pool-9-thread-1] - unconfigured columnfamily gdelt_chunkmap
[2015-12-19 06:42:32,179] ERROR com.websudos.phantom [pool-9-thread-2] - unconfigured columnfamily gdelt_chunkmap
[2015-12-19 06:42:32,308] ERROR com.websudos.phantom [pool-9-thread-1] - unconfigured columnfamily gdelt_chunkmap

**Comment by velvia** [comment] 2015-12-19 21:24
Hi Noorul,

Thanks for trying.  Did you follow the directions and do a filo-cli init, and then create and define a dataset?  The exception looks like the init and table creation steps were not followed.  If the docs are not clear enough about this we can clean it up. 

Note that in Spark you don't have to create a table and column schema explicitly, but still need to do an init.  

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by noorul** [comment] 2015-12-20 04:52
I am trying to follow https://github.com/tuplejump/FiloDB#cli-example

**Comment by velvia** [comment] 2015-12-20 08:31
Would you mind sharing the sequence of steps you followed and the output that you got?    (leading up to the error you saw).

thanks.

**Comment by noorul** [comment] 2015-12-20 15:48
I followed cli example

./filo-cli --command create --dataset gdelt --columns GLOBALEVENTID:int,SQLDATE:string,MonthYear:int,Year:int,FractionDate:double,Actor1Code:string,Actor1Name:string,Actor1CountryCode:string,Actor1KnownGroupCode:string,Actor1EthnicCode:string,Actor1Religion1Code:string,Actor1Religion2Code:string,Actor1Type1Code:string,Actor1Type2Code:string,Actor1Type3Code:string,Actor2Code:string,Actor2Name:string,Actor2CountryCode:string,Actor2KnownGroupCode:string,Actor2EthnicCode:string,Actor2Religion1Code:string,Actor2Religion2Code:string,Actor2Type1Code:string,Actor2Type2Code:string,Actor2Type3Code:string,IsRootEvent:int,EventCode:string,EventBaseCode:string,EventRootCode:string,QuadClass:int,GoldsteinScale:double,NumMentions:int,NumSources:int,NumArticles:int,AvgTone:double,Actor1Geo_Type:int,Actor1Geo_FullName:string,Actor1Geo_CountryCode:string,Actor1Geo_ADM1Code:string,Actor1Geo_Lat:double,Actor1Geo_Long:double,Actor1Geo_FeatureID:int,Actor2Geo_Type:int,Actor2Geo_FullName:string,Actor2Geo_CountryCode:string,Actor2Geo_ADM1Code:string,Actor2Geo_Lat:double,Actor2Geo_Long:double,Actor2Geo_FeatureID:int,ActionGeo_Type:int,ActionGeo_FullName:string,ActionGeo_CountryCode:string,ActionGeo_ADM1Code:string,ActionGeo_Lat:double,ActionGeo_Long:double,ActionGeo_FeatureID:int,DATEADDED:string,Actor1Geo_FullLocation:string,Actor2Geo_FullLocation:string,ActionGeo_FullLocation:string --sortColumn GLOBALEVENTID

./filo-cli --command list --dataset gdelt - works 

./filo-cli --command importcsv --dataset gdelt --filename GDELT-1979-1984-100000.csv -fails

**Comment by velvia** [comment] 2015-12-21 00:29
@noorul hmmm, I'm not able to reproduce it.  What is the output after the first two steps?

If you use cqlsh to log in, and do `use filodb; describe tables;` what do you see?

**Comment by velvia** [comment] 2016-02-17 22:42
@noorul feel free to reopen if you see this with master; lots of changes have gone in so ingestion should be much more stable now.

**Closed by velvia** 2016-02-17 22:42 UTC
